grid:
  width: 40
  height: 40
  cell:
    width: 15
    height: 15

obstacles:
  single: 25

grass: 800

clock:
  ticks: 10
  generation_size: 150

animats:
  count:
    easy_prey: 25
    hard_prey: 20
    predator: 5
    best_predator: 5
  range:
    easy_prey: 5
    hard_prey: 5
    predator: 5
  speed:
    easy_prey: 3
    hard_prey: 4
    predator: 5



