grid:
  width: 40
  height: 40
  cell:
    width: 15
    height: 15

obstacles:
  single: 25

grass: 800

clock:
  ticks: 10

animats:
  count:
    easy_prey: 5
    hard_prey: 5
    predator: 3
  range:
    easy_prey: 5
    hard_prey: 5
    predator: 5



